name: Create Release Branch
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: release
